### ISSUE TITLE
DEBUG messages showing

### ISSUE THREAD

**Issue by chriskacerguis** [maintux/knife-esx#2]
Hello,

When I installed your plugin knife started to show DEBUG message when running any knife command (they stopped when I removed the knife-esx plugin).  So, it seems to be ignoring the log_level setting from within .chef/knife.rb

**Comment by maintux** [comment]
Hi, thanks for reporting this. I'll check asap

**Comment by tommyblue** [comment]
The messages come from Celluloid. For some reason its default log level is DEBUG. I'm fixing it

**Comment by tommyblue** [comment]
@maintux if you think the commit is ok I can merge it

**Comment by maintux** [comment]
@tommyblue I'm not sure that this

```
include Celluloid
Celluloid.logger = Chef::Log.logger
```

is still usefull, because you use directly `Chef::Log.logger` instead of `CLogger`

**Comment by tommyblue** [comment]
`Celluloid.logger = Chef::Log.logger` is the line which removes debug messages. I removed `CLogger` while trying to understand the reason of the debug messages, but using `Chef::Logger` doesn't resolve the problem, because the messages come from Celluloid and not from the `knife-esx` gem itself. The reason why Celluloid prints debug messages is obscure to me, but changing its logger with the Chef one resolves this bug

**Comment by maintux** [comment]
Try to remove `require 'celluloid'` and even `include Celluloid`

**Comment by tommyblue** [comment]
works great! pushing
